baseURL = "https://your-site.netlify.app/"
languageCode = "en-us"
title = "Marieth Coetzer"
# Note: no 'theme' line, since we're using custom layouts

# Optional: generate pretty URLs without .html
[permalinks]
  blog = "/blog/:slug/"

[params]
  author = "Marieth Coetzer"
  heroTitle = "Alex Doe"
  heroSubtitle = "Blog and Portfolio"
  aboutText = "Aspiring Data Scientist with a passion for uncovering insights from data and building intelligent solutions. Welcome to my personal space where I share my projects, thoughts, and journey into the world of data."
